name: build push deploy presentation site

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    name: Build, Push, Deploy
    runs-on: ubuntu-latest

    steps:
      - name: install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: dockerhub login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: checkout
        uses: action/checkout@v2
      
      - name: build
        run: |
          make build-production

      - name: push
        run: |
          make push-production

      - name: deploy
        run: |
          make run-production